import { createClient } from '@supabase/supabase-js';
import { Event, Alumni, Branding, HeroContent, MissionContent, CommitteeMember, ContactInfo, MerchandiseItem, GalleryContent, Order } from '../types';
import { EVENTS_DATA, INITIAL_ALUMNI_DATA, BRANDING, HERO_CONTENT, MISSION_STATEMENT, COMMITTEE_LEADERSHIP, COMMITTEE_MEMBERS_LIST, CONTACT_INFO, SHOP_ITEMS, GALLERY_CONTENT } from '../assets';

// ==========================================
// 🔌 DATABASE CONNECTION SETUP
// ==========================================

// Safely retrieve environment variables
const getEnv = () => {
  try {
    return (import.meta as any).env || {};
  } catch {
    return {};
  }
};

const env = getEnv();
const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_KEY = env.VITE_SUPABASE_KEY;

// AUTO-DETECT: If keys exist and aren't placeholders, use Real Database.
const useRealDatabase = 
  !!SUPABASE_URL && 
  !!SUPABASE_KEY && 
  !SUPABASE_URL.includes('YOUR_PROJECT_ID') &&
  !SUPABASE_URL.includes('PLACEHOLDER');

// Initialize Supabase
const supabase = useRealDatabase 
  ? createClient(SUPABASE_URL, SUPABASE_KEY) 
  : null;

console.log(`Database Mode: ${useRealDatabase ? '🟢 Connected to Supabase' : '🟠 Local Storage (Demo Mode)'}`);

// ==========================================
// 🛠️ SQL SETUP SCRIPT (Run in Supabase)
// ==========================================
/*
  1. Events Table:
  create table events (
    id bigint generated by default as identity primary key,
    title text,
    date text,
    location text,
    description text,
    image text,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  2. Alumni Table:
  create table alumni (
    id bigint generated by default as identity primary key,
    name text,
    graduation_year int,
    profession text,
    location text,
    email text,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  3. Site Content Table (For Logo, Committee, Shop, etc.):
  create table site_content (
    id int primary key,
    data jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );
  
  4. Orders Table (New):
  create table orders (
    id bigint generated by default as identity primary key,
    customer_name text,
    customer_email text,
    customer_phone text,
    items jsonb,
    total_amount numeric,
    status text,
    date text,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  -- IMPORTANT: Run this insert once to initialize the row
  insert into site_content (id, data) values (1, '{}');
*/

// ==========================================
// 📦 TYPES FOR FULL SITE DATA
// ==========================================
export interface SiteData {
  branding: Branding;
  heroContent: HeroContent;
  missionContent: MissionContent;
  galleryContent: GalleryContent;
  committeeLeadership: CommitteeMember[];
  committeeMembersList: string[];
  contactInfo: ContactInfo;
  shopItems: MerchandiseItem[];
}

// Default data fallback
const DEFAULT_SITE_DATA: SiteData = {
  branding: BRANDING,
  heroContent: HERO_CONTENT,
  missionContent: MISSION_STATEMENT,
  galleryContent: GALLERY_CONTENT,
  committeeLeadership: COMMITTEE_LEADERSHIP,
  committeeMembersList: COMMITTEE_MEMBERS_LIST,
  contactInfo: CONTACT_INFO,
  shopItems: SHOP_ITEMS
};

// ==========================================
// 📦 DATA SERVICE
// ==========================================

export const db = {
  
  // --- SITE CONTENT (Logo, Committee, Shop, etc.) ---

  getSiteContent: async (): Promise<SiteData> => {
    if (useRealDatabase && supabase) {
      const { data, error } = await supabase.from('site_content').select('data').eq('id', 1).single();
      
      if (error || !data || !data.data || Object.keys(data.data).length === 0) {
        // If empty or error, return defaults (and maybe save them to init DB)
        return DEFAULT_SITE_DATA;
      }
      
      // Merge with defaults to ensure all fields exist if schema changes
      return { ...DEFAULT_SITE_DATA, ...data.data };
    } else {
      const saved = localStorage.getItem('msvosa_site_content');
      if (saved) return { ...DEFAULT_SITE_DATA, ...JSON.parse(saved) };
      return DEFAULT_SITE_DATA;
    }
  },

  saveSiteContent: async (content: SiteData) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase
        .from('site_content')
        .upsert({ id: 1, data: content });
      
      if (error) {
        console.error("Supabase Save Error:", error);
        throw error;
      }
    } else {
      try {
        localStorage.setItem('msvosa_site_content', JSON.stringify(content));
      } catch (e) {
        alert("Local Storage Full! Photos might be too large. Please setup Supabase Database.");
      }
    }
  },

  // --- EVENTS ---
  
  getEvents: async (): Promise<Event[]> => {
    if (useRealDatabase && supabase) {
      const { data, error } = await supabase.from('events').select('*').order('id', { ascending: false });
      if (error) { console.error(error); return []; }
      return data || [];
    } else {
      const saved = localStorage.getItem('msvosa_events');
      if (saved) return JSON.parse(saved);
      return EVENTS_DATA;
    }
  },

  addEvent: async (event: Omit<Event, 'id'>) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('events').insert([event]);
      if (error) throw error;
    } else {
      const current = await db.getEvents();
      const newEvent = { ...event, id: Date.now() };
      const updated = [newEvent, ...current];
      localStorage.setItem('msvosa_events', JSON.stringify(updated));
      return newEvent;
    }
  },

  deleteEvent: async (id: number) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('events').delete().eq('id', id);
      if (error) throw error;
    } else {
      const current = await db.getEvents();
      const updated = current.filter(e => e.id !== id);
      localStorage.setItem('msvosa_events', JSON.stringify(updated));
    }
  },

  // --- MEMBERS (ALUMNI) ---

  getMembers: async (): Promise<Alumni[]> => {
    if (useRealDatabase && supabase) {
      const { data, error } = await supabase.from('alumni').select('*').order('created_at', { ascending: false });
      if (error) { console.error(error); return []; }
      return data || [];
    } else {
      const saved = localStorage.getItem('msvosa_alumni_directory');
      if (saved) return JSON.parse(saved);
      return INITIAL_ALUMNI_DATA;
    }
  },

  addMember: async (member: Omit<Alumni, 'id'>) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('alumni').insert([
        { 
          name: member.name, 
          graduation_year: member.graduationYear, 
          profession: member.profession,
          location: member.location 
        }
      ]);
      if (error) throw error;
    } else {
      const current = await db.getMembers();
      const newMember = { ...member, id: Date.now().toString() };
      const updated = [newMember, ...current];
      localStorage.setItem('msvosa_alumni_directory', JSON.stringify(updated));
      return newMember;
    }
  },

  deleteMember: async (id: string) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('alumni').delete().eq('id', id);
      if (error) throw error;
    } else {
      const current = await db.getMembers();
      const updated = current.filter(m => m.id !== id);
      localStorage.setItem('msvosa_alumni_directory', JSON.stringify(updated));
    }
  },

  // --- ORDERS ---

  getOrders: async (): Promise<Order[]> => {
    if (useRealDatabase && supabase) {
      const { data, error } = await supabase.from('orders').select('*').order('created_at', { ascending: false });
      if (error) { console.error(error); return []; }
      
      // Map Snake Case DB to Camel Case TS
      return data.map((d: any) => ({
        id: d.id,
        customerName: d.customer_name,
        customerEmail: d.customer_email,
        customerPhone: d.customer_phone,
        items: d.items,
        totalAmount: d.total_amount,
        status: d.status,
        date: d.date
      }));
    } else {
      const saved = localStorage.getItem('msvosa_orders');
      if (saved) return JSON.parse(saved);
      return [];
    }
  },

  addOrder: async (order: Omit<Order, 'id'>) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('orders').insert([{
        customer_name: order.customerName,
        customer_email: order.customerEmail,
        customer_phone: order.customerPhone,
        items: order.items,
        total_amount: order.totalAmount,
        status: order.status,
        date: order.date
      }]);
      if (error) throw error;
    } else {
      const current = await db.getOrders();
      const newOrder = { ...order, id: Date.now() };
      const updated = [newOrder, ...current];
      localStorage.setItem('msvosa_orders', JSON.stringify(updated));
    }
  },

  updateOrderStatus: async (id: number, status: 'Completed' | 'Cancelled') => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('orders').update({ status }).eq('id', id);
      if (error) throw error;
    } else {
      const current = await db.getOrders();
      const updated = current.map(o => o.id === id ? { ...o, status } : o);
      localStorage.setItem('msvosa_orders', JSON.stringify(updated));
    }
  },

  deleteOrder: async (id: number) => {
    if (useRealDatabase && supabase) {
      const { error } = await supabase.from('orders').delete().eq('id', id);
      if (error) throw error;
    } else {
      const current = await db.getOrders();
      const updated = current.filter(o => o.id !== id);
      localStorage.setItem('msvosa_orders', JSON.stringify(updated));
    }
  }
};